### ISSUE TITLE
Client issues to generate jar file

### ISSUE THREAD

**Issue by HendGedawy** [bnnthang/FederatedLearningTestbed#14]
Fix client issues to generate jar file. Also explain in the README the steps exactly.

**Comment by ttanv** [comment]
Sorry could you remind me what the issues exactly were?

**Comment by thangnbn** [comment]
> Sorry could you remind me what the issues exactly were?

@HendGedawy Can you check if this issue still exists and elaborate on this issue?

**Comment by HendGedawy** [comment]
No it is fine now
