### ISSUE TITLE
Cifar10Repository in server does not comply with single responsibility principle

### ISSUE THREAD

**Issue by thangnbn** [bnnthang/FederatedLearningTestbed#26]
Same as what is mentioned in #24. Check https://github.com/bnnthang/RealFL/blob/a58ff2b0a21876baa608cedce62f225a053203a7/Server/src/main/java/com/bnnthang/fltestbed/Server/Repositories/Cifar10Repository.java.

**Comment by thangnbn** [comment]
Partially fixed in commit c47ccf5.

@tem556 Please check and complete replacing other places. This has a lower priority than other issues.

**Comment by ttanv** [comment]
@bnnthang I believe this issue can be closed now
